// Generated by https://quicktype.io

export interface News {
    id:              number;
    titleNews:       string;
    mpNews:          string;
    descriptionNews: string;
    created_at:      string;
    updated_at:      string;
    img_path:        string;
    stateNews:       string;
}
